[package]
name = "parser"
version.workspace = true
edition.workspace = true

[dependencies]
ropey.workspace = true
serde = { workspace = true, features = ["derive"] }
toml.workspace = true
serde_json.workspace = true
taplo.workspace = true
url.workspace = true
difference = "2.0.0"
